variable "aws_region" {}
variable "env" {}
variable "source_bucket_name" {}
variable "processed_bucket_name" {}
variable "iam_role" {}
variable "lambda_name" {}
variable "inline_policy_name" {}
variable "lambda_zip_path" {}
variable "lambda_runtime" {}
